### ISSUE TITLE
ttml play issue №2

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1207]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:yes

**What version of Shaka Player are you using**2.3.0

**Can you reproduce the issue with our latest release version**:yes

**Can you reproduce the issue with the latest code from `master`**:yes

**Are you using the demo app or your own custom app**:own

**If custom app, can you reproduce the issue using our demo app**:cannot because of CORS

**What browser and OS are you using**:win7x64-chrome\firefox

**What are the manifest and license server URIs**:sent to mail
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?** Opened stream, pressed CC.

**What did you expect to happen?** Player have to download captions.

**What actually happened?** I see how palyer fetches only audio and video

P.s. in https://github.com/google/shaka-player/issues/1028 was same issue, and until 2.3.0 it worked.

**Comment by TheModMaker** [comment]
I am unable to reproduce.  I see that there are errors because of #1204, which has been fixed.  If I try the nightly site, it seems to work fine.  Note that we will only download subtitle/caption tracks when the captions are shown and only when you use `player.setTextTrackVisibility`, meaning if you use the default browser controls it won't work.  Can you try again from the nightly?

https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by kuznetcoff777** [comment]
In nightly version it works properly, what stable version will it be and when it will be available?

**Comment by TheModMaker** [comment]
It will be available in v2.3.1 (and probably v2.2.10), which will be released in a week or two.

**Comment by kuznetcoff777** [comment]
@TheModMaker 
Hi. Am i correctly understand that in 2.3.1 this issue was not fixed? When will it be fixed then?

**Comment by joeyparrish** [comment]
This was a duplicate of #1204, and the fixes for #1204 were cherry-picked for v2.3.1 and v2.2.10.  Either of those releases should work for you.

**Comment by kuznetcoff777** [comment]
Sorry, my fault, everything is ok
