### ISSUE TITLE
Error in remapping segmenttimeline when going from live to VoD

### ISSUE THREAD

**Issue by TobbeEdgeware** [google/shaka-player#1458]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes. It seems that Issue #1055 is related.

**What version of Shaka Player are you using?**:
Latest from master: 58d1498

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome 66, Mac OS High Sierra

**What are the manifest and license server URIs?**:
https://vm2.dashif.org/livesim/segtimeline_1/startrel_-20/stoprel_20/timeoffset_0/testpic_2s/Manifest.mpd

**What did you do?**
I tried to play the URL and the player stalls after around 30s. 

**What did you expect to happen?**
This URL is a start-over content that should start 20s before wall-clock and end 20s after wall-clock. It is live, and will become VoD (type=static) 20s into the future.

It works nicely to play the corresponding asset which uses Number template:
https://vm2.dashif.org/livesim/startrel_-20/stoprel_20/timeoffset_0/testpic_2s/Manifest.mpd

In this case the asset plays until end, stops, and it is possible to rewind to the start.

**What actually happened?**
For SegmentTimeline URL, the one reported, most of the time, the player stalls somewhere around 30s into the to be 40s buffer. It seems that the SegmentTimes are read in a somewhat different way when the manifest is static.

The assert   `shaka.media.SegmentIndex.assertCorrectReferences_(newReferences);`  fired.

Looking into the values of references and newReferences it seems that 

newReferences has startTimes =  [0, 0.005333, 2.010666, 4.016, 6, ...] while references has startTimes = [0, 2.010666, 4.016, 6, ...] , so newReferences has gotten an extra startTime, although they should have the same list (newReferences from a static mpd and references from a dynamic).

In general, these startTimes look like a mixture of video and audio startTimes, since video all start at exact seconds compared to the period start, while the audio start as soon as possible after the video (maximum 16ms).

Some remarks. The idea to use a Location element for this stems from @joeyparrish. I think it would be good to include the two streams (with Number and SegmentTimeline) in your test assets under DASH-IF, since I intend to keep them available there.

**Comment by michellezhuogg** [comment]
Hi @TobbeEdgeware ,
Thank you for reporting this! I am able to reproduce this issue in Chrome on MacOS, but not in Firefox on MacOS or linux. We will work on fixing it!

**Comment by vaage** [comment]
@TobbeEdgeware thank you for your patience with this issue.

I can reproduce it when I use the commit hash you provided. When I use the [current master](https://github.com/google/shaka-player/commit/1b150eef042443bc38b45a1808e5fb5ffc51da83), I cannot reproduce it. So it looks like it was fixed by another commit.

Could you try reproducing the issue using the [current master](https://github.com/google/shaka-player/commit/1b150eef042443bc38b45a1808e5fb5ffc51da83). If everything works as you would expect, please feel free to close the issue.

**Comment by TobbeEdgeware** [comment]
@vaage Sounds good. I'm on vacation until Aug. 6, but will try to look at this right when I'm back if not sooner.

**Comment by vaage** [comment]
@TobbeEdgeware Thanks. I am going to put the "waiting on response" label back on so that our book keeping won't think that we are ignoring the issue.

**Comment by TobbeEdgeware** [comment]
@vaage I agree that the problem is gone (tested in version 2.4.3). In Chrome 68, I can still see the issue in 58d1498 but not in version 2.4.3. Thus, you can close this issue.

**Comment by vaage** [comment]
Thanks @TobbeEdgeware for checking.
