### ISSUE TITLE
Playback Speed resets to 1x 

### ISSUE THREAD

**Issue by sradhanjan** [google/shaka-player#3261]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.0.10, can also be seen in demo app 

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**What browser and OS are you using?**
Chrome and Windows 10 

**What did you do?**
compile the code 
create simple html page with myapp.js
open the page on browser
change playback speed
press pause button

**What did you expect to happen?**
When the video is resumed playback speed should remain intact

**What actually happened?**
Playback speed resets to 1x speed

screenshots for better understanding
(changed the speed)
![image](https://user-images.githubusercontent.com/56840012/111895819-2990ef80-8a3b-11eb-8e79-90acf815f38f.png)

paused the video (speed resets to 1x)
![image](https://user-images.githubusercontent.com/56840012/111895841-50e7bc80-8a3b-11eb-98bd-4de4d6fe0ad9.png)

**Comment by sradhanjan** [comment]
I would like to work on this issue, please guide me for the same

**Comment by surajkumar-sk** [comment]
@sradhanjan it's Sunday. and members of this project usually don't work on Saturday and Sunday. so they will guide you on Monday PDT. I don't know if this speed reset is intentional or not, but it does seem like a mistake. As far as I understand this issue, this could probably be fixed by changing a few lines in `ui/playback_rate_selection.js`, try understanding that file, you will find a solution for the problem. I am not sure if it's a bug or intentional, so it's up to you whether to work on it or not. if you start working on it start with `ui/playback_rate_selection.js` this file then `ui/controls.js` and figure out why that's happening.

**Comment by sradhanjan** [comment]
@surajkumar-sk Ok in a mean time I will try to understand the code base and wait for the response from the members of this project

**Comment by nbcl** [comment]
Hello @sradhanjan!

Although, as @surajkumar-sk said, it would be best for you to wait for a  maintainer to give you guidance, as a fellow student I understand that the weekend is probably the period we have the most time to contribute, so I tried my best to give you advice to help you get started.

I was able to reproduce this bug by clicking the small button and the video screen, but also, I realized this happened even when you changed the playback rate on a paused video and then pressed "play", so we should start by checking `play_button.js`.

https://github.com/google/shaka-player/blob/c5af2be27a2256e699763e0570235b30838ed2aa/ui/play_button.js#L72-L78

As you can see, we are calling for `playPausePresentation()`, which, among other things, does the following:

https://github.com/google/shaka-player/blob/c5af2be27a2256e699763e0570235b30838ed2aa/ui/controls.js#L606-L612

Removing `this.player_.cancelTrickPlay()` fixes the problem on every possible case I could imagine, so let us continue by checking out what it does.

https://github.com/google/shaka-player/blob/c5af2be27a2256e699763e0570235b30838ed2aa/lib/player.js#L3169-L3178

Lines 3171 and 3175 are causing the behavior that you described.

Gathering all the information I indicated before, and if I understand correctly, it appears to be that every time the play button is clicked the playback rate is changed to x1.0 by default.

Now, of course, I am not saying that the solution should necessarily be achieved by removing `this.player_.cancelTrickPlay()`  or some instance of `this.playRateController_.set(1);`, but with the source of the issue, I think the problem should become a bit more approachable.

Once again, I would advice to wait for a maintainer to answer this issue, but I hope this can help you get started.

Please let me know if you need anything else!

**Comment by sradhanjan** [comment]
@nbcl Thanks a lot for the guidance, I will try to fix the issue with this approach after any member of this project confirms that this is a bug and need to be fixed.

**Comment by joeyparrish** [comment]
Definitely a bug, and definitely a bug in the UI somewhere.  Doing the equivalent using the API does not recreate the issue:

```js
video.playbackRate = 2;
video.pause();
video.play();
```

In fact, if you set the playback rate in the UI, then pause and play via the video API, everything is still fine.  So I suspect the issue would be in the play/pause button in the UI, though it could be a more subtle interaction elsewhere.

Thanks @sradhanjan, for the report, and thanks also for working on a fix!

**Comment by joeyparrish** [comment]
After some further consideration, I think I recall why we call cancelTrickPlay().  This is meant to work in concert with the fast-forward and rewind buttons (non-default).  If the user is fast-forwarding, then clicking play/pause should go back to a playbackRate of 1.  ("Trick play" is an industry term for fast-forwarding or rewinding, in the way that you would do with old VHS tapes.  Though I don't know how many of you are old enough to remember VHS.)

Some time after the non-default fast-forward and rewind buttons, the speed control was added.  This is different from the fast-forward, in that it indicates a user intent that should not change state based on other parts of the UI.  When the user says "play at 2x", they want it to stay that way.

It seems to me that the solution should be to have Player track trick mode state.  If playbackRate was set in some way other than through player.trickPlay(), cancelTrickPlay() should do nothing.

**Comment by surajkumar-sk** [comment]
@joeyparrish i am not old enough but my grandpa does have a VHS, with some retro speeches and music and few video recording of his time. 😁

**Comment by joeyparrish** [comment]
I never had a record player or 8-track, but I had cassette tapes and VHS before CDs and DVDs.  I somehow missed the LaserDisc fad.  :-)

Back to playback rate, there is one more way I found, leveraging a feature built into the browser:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/defaultPlaybackRate

In the UI control for playback rate, we could set both playbackRate and defaultPlaybackRate.  In cancelTrickPlay() or anywhere else we set playbackRate to 1, it would instead be set to defaultPlaybackRate.  `git grep playbackRate` should help locate all such places, though you may have to trace through the call stack from there to find where the values are generated.

**Comment by surajkumar-sk** [comment]
Hello @sradhanjan ,
do you still intend to work on this ?

**Comment by sradhanjan** [comment]
@surajkumar-sk I am still figuring out the solution to fix this issue but if you want feel free to work on it.

**Comment by surajkumar-sk** [comment]
@sradhanjan i was just clarifying that someone's working on it , so other's can work on something else. Keep working and feel free to ask for help.

**Comment by sradhanjan** [comment]
@surajkumar-sk I have noticed even after deleting `control.js` or `play_button.js` from ui folder there are no changes to the html page and video is still working. How is that possible?

**Comment by surajkumar-sk** [comment]
@sradhanjan when you run `python build/all.py` all the files of this project gets compiled, checked for errors, and then a new folder dist is created and all the compiled files are added into that folder, which means the whole projects is in that dist folder which can be used by users to create their application. when you delete those files nothing happens because the files of the project which you are using for creating the HTML file are in the dist folder. for viewing updates on any change made in the code you will have to run `python build/all.py`  again, this will update the dist folder and thus your HTML file. now that you deleted files running that command will give an error of files missing.

**Comment by sradhanjan** [comment]
@surajkumar-sk Ok so whatever changes I make in the code base I will have to compile the program again using 
`python build/all.py` right?

**Comment by surajkumar-sk** [comment]
@sradhanjan yes

**Comment by sradhanjan** [comment]
@joeyparrish @surajkumar-sk The issue has been fixed, now working on the pull request

**Comment by TheModMaker** [comment]
You do NOT need to rebuilt when you make changes if you use the uncompiled library.  If you are using our demo, then it uses the uncompiled library by default.  You only need to rebuild if you are using `shaka-player.compiled.js`.

Note that the browser will probably cache files, so even if you refresh the page, you may still see the old files.  You either need to clear the browser cache or disable caching on your web server.  You can do this by setting the `Cache-Control: no-cache` response header on your server.  Check your web server docs on how to do this.

**Comment by joeyparrish** [comment]
You can also conveniently disable caching in your browser while doing development.  The chrome dev tools has a "disable cache" option in the network panel.  With that option checked, cache is disabled any time dev tools is open, and re-enabled when dev tools is closed (during normal browsing).  Hope that helps!

**Comment by Sayan-dev** [comment]
The bug still  exists . I might be able to fix this. Shall I proceed?

**Comment by joeyparrish** [comment]
Doesn't look like there are any open PRs for this right now.  I made suggestions on an approach here: https://github.com/google/shaka-player/issues/3261#issuecomment-804206315  Though I could also be wrong.  Have fun!

**Comment by surajkumar-sk** [comment]
@joeyparrish correct me if I am wrong, In your comment [#3261 (comment)](https://github.com/google/shaka-player/issues/3261#issuecomment-804206315) you said 
>> In the UI control for playback rate, we could set both playbackRate and defaultPlaybackRate. In cancelTrickPlay() or anywhere else we set playbackRate to 1, it would instead be set to defaultPlaybackRate. git grep playbackRate should help locate all such places, though you may have to trace through the call stack from there to find where the values are generated.
But defaultPlaybackRate still returns 1 which is already being set. and the playback speed resets, I might have missed something because i didnt understand the last part .

And also with my previous PR experiences, I would like to discuss my solution before adding a PR, and get an idea about where I am going wrong:
1. The cancel trick play was added to reset video speed when the video is paused during fast-forwarding and rewinding.

2. Now that playback speed has been added we need to restrict the cancel trick play to be executed only when the video is being controlled by fast-forwarding and rewinding.

3. In the present Shaka-player code `cancelTrickPlay()` is called inside `playPausePresentation()` which runs when video is paused. we need to add an if condition to avoid it from running when the speed is set in playback speed menu. 

4. For this i would like to create a variable `cancelTrickPlayRequired` inside `controls,js` which becomes true when playback is controlled by fast forward and rewind and false when playback speed is controlled using speed menu. 
5. `fast_forward_button.js`, `rewind_button.js`, `playback_rate_selection.js` will dispatch an event when there buttons are clicked. we can listen to these events in ` control.js` and alter the value of `cancelTrickPlayRequired` variable and run cancel trick play only when its need inside `playPausePresentation()`.

will this be too complicated? there are a lot of files being changed.

**Comment by michellezhuogg** [comment]
> will this be too complicated? there are a lot of files being changed.

Kind of, however thank you for looking into the issue and trying to fix it!
We have a fix for it and will be out soon :)

**Comment by surajkumar-sk** [comment]
I am starting with lib files tommorow. I am done trying to solve issues within ui.
