### ISSUE TITLE
subtitle using low latency canvas instead of DOM

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-player#3432]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
I been notice that on chrome, subtitle don't work as expected, I manually sync subtitle with sounding. However when playing, the behavior are undeterministic - sometimes it work perfectly, some other time it get delay 0.5 or as much as 1s. (tweaking around with https://github.com/google/shaka-player/blob/master/lib/text/ui_text_displayer.js#L69 does not help).

This behavior do not happen on Firefox or VLC or MPV (it does on Edge - I suspect all chromium based will get this).

**Describe the solution you'd like**
For something as sensitive as sound and subtitle, I suggest we use low latency canvas https://developers.google.com/web/updates/2019/05/desynchronized

I'm already working on custom build with custom dom-util module and many thing - But I'll try to make it work first.

**Additional context**
touch https://github.com/google/shaka-player/issues/3188

**Comment by theodab** [comment]
A separate text displayer plugin for this would be possible. It'd be a lot of work, though. I don't think there's any native way to draw DOM elements in a canvas (their example of the video playing in a canvas is actually just drawing copying the actual video element into the canvas every 20s), so the text displayer plugin would need to have its own rendering logic.

I'm also a bit concerned by [this section](https://developers.google.com/web/updates/2019/05/desynchronized#alpha_channels):

> A translucent canvas element, one where alpha is set to true, can still be desynchronized, but it must not have any other DOM elements above it.

A text displayer plugin that's based on a canvas is going to have to have a transparent background, so that the video element and the UI and such can go beneath it. In our UI, the text container does sit on top of every other DOM element inside the video container, so it's not going to be occluded by anything else. However, for developers using Shaka Player, that could easily be a source of confusing problems.

**Comment by kocoten1992** [comment]
> In our UI, the text container does sit on top of every other DOM element inside the video container, so it's not going to be occluded by anything else.

Just realize we have `.shaka-controls-container` with `z-index: 1`, that is on top of everything
If I change `.shaka-text-container` to `z-index: 2`, I can even select the subtitle text :laughing:

**Comment by theodab** [comment]
> > In our UI, the text container does sit on top of every other DOM element inside the video container, so it's not going to be occluded by anything else.
> 
> Just realize we have `.shaka-controls-container` with `z-index: 1`, that is on top of everything
> If I change `.shaka-text-container` to `z-index: 2`, I can even select the subtitle text 😆

Ah, that's a good point. I had forgotten about `z-index`.

I tried testing this in our UI, to see what exactly is expected to go wrong if another DOM element is on top of the canvas. Just a little barebones example, a canvas element that copies the video state into a box in the corner of the video. But it turns out that low latency canvas isn't supported in Chrome on Mac yet; ChromeOS and Windows only at the moment, according to MDN.

**Comment by kocoten1992** [comment]
quick update, I manage to get it working - with or without `desynchronized` to my eye and ear, sub and sound perfectly sync with each other, this suggest we don't have to use desynchronized and could avoid the whole z-index issue.

**Comment by kocoten1992** [comment]
It work now :smile: , will start compose pull request

**Comment by TheModMaker** [comment]
I don't think this should be merged into the repo.  This is a complex feature that adds little difference.  I would want to double check that this is actually caused by browser latency and can't be fixed in the normal text displayer.

First, check that the times in the Cue object match the expected times.  You check the `append(cues)` method on the displayer to check the `cue.startTime` value to see if it matches what you expect.  Your encoder could be adjusting the times slightly or we could be parsing it incorrectly.

If the times are correctly, you should check the delay between when the video time changes and the cue appears.  You can use the `timeupdate` event to accurately get when the video time updates.  You can record your screen to see how long it takes.

```js
video.addEventListener('timeupdate', () => {
  if (video.currentTime >= 4.56) {  // Use the value of cue.startTime here
    console.log('Hit');
    video.pause();
  }
});
```

You can also update the `updatePeriod` you linked to to reduce the delay when updating the cues.  Setting to 0.001 would make the delay non-existent.

I'd also suggest adding logs to `updateCaptions_` to see when we update the cues.  You could also check how long the method takes to see if it takes a long time and causing latency.  You can use `Date.now()` to get the millisecond current time to measure how long the method takes.

**Comment by kocoten1992** [comment]
@TheModMaker , I done most of that, let me explain below and I can prove it to you:
- I console.log the `cue.payload text` and see if DOM text appear on the screen relative close to console.log, the result is - sometime it is, sometime it is not - the most extreme case is it getting delayed almost a second (or not appear at all - because it already pass time it should) - I dig into css too to see if we have any transition effect, but setting to 0ms to all have no effect (I'm not very good with CSS - I check using `computed tab` on transition.
- setting `updatePeriod` doesn't work either - that lead me to believe that is a chrome bug - because even leave `0.25`, on firefox it work correctly.
- I don't have a reliable way to measure the delay, however I can do this, I will write a `canvas_feat_ui_text_displayer.js`, and display both text at the same time using the same config, and video clip it - you will get that.

**Comment by kocoten1992** [comment]
So...This is the code https://gist.github.com/kocoten1992/3ce134d7dd977e623193854e9d24d953, but I've figure out the root core reason of this - and I've fix it.

![Screenshot from 2021-06-02 05-27-17](https://user-images.githubusercontent.com/7130705/120397826-3b5c1080-c363-11eb-8bd4-ff93d79c6914.png)

This surprisingly is caused by `bad content`, when audio and video out-of-sync - somehow chrome internal bug and causing subtitle out of sync with audio too.

Timeline of event:
1. video and audio encode (mistakenly encode audio without `aresample=async=1000`)
2. notice strange behavior on chrome subtitle
3. report bug
4. test out canvas/svg (and canvas are not effect by `bad content`)
5. notice after watching for a while, audio mis-sync with video
6. reencode audio with `aresample=async=1000` + generate new mpd
7. write `canvas_feat_ui_text_displayer.js`
8. notice the problem is gone after fix audio encoding

The fix is to apply https://github.com/google/shaka-player/issues/2810#issuecomment-695169959

I'm sorry for wasting everyone time on this :sob:

**Comment by joeyparrish** [comment]
Thank you for updating us on the outcome!  Not a waste of our time at all, and we have certainly learned something.  Also, I really appreciate your taste in movies.  (Ravenclaw for life.)

**Comment by kocoten1992** [comment]
Hello @joeyparrish  , @TheModMaker 

When I thought it was cause by audio mis-sync, I was mistaken again :(!

Because when I switch back to default `ui_text_displayer.js`, the problem is still there.

Then I think why the hell `canvas_feat_ui_text_displayer.js` cannot caught that, I tinker with it for a whole day and conclude that - it because the position of canvas relative to text div. If the position of canvas is on top of text div, chrome get it right, otherwise, please check my video.

Honestly, without this video, it start sound like I'm seeing thing. (I'm not recordind sound - it irrelevant - however the big white text in canvas 100% display on point).

So to fix this issue it relative easy, just have a canvas on top of text div (even it does nothing), I would like to hear your opinion first!

https://user-images.githubusercontent.com/7130705/120714196-1a272b80-c4ed-11eb-88bf-671ab65fe06c.mp4

![image](https://user-images.githubusercontent.com/7130705/120714859-fc0dfb00-c4ed-11eb-9e61-99651d1a38d6.png)

**Comment by TheModMaker** [comment]
I'll reopen, but I'm still not entirely convinced this is the problem.  Can you reproduce with one of our sample assets or can you send us the asset you are testing with?  You can send it privately to <shaka-player-issues@google.com> if you can't share it publicly.

How long does the `updateCaptions_` method take?  Can you run Chrome profiler and see what is happening?  If this is DOM layout delay, I'd expect to see a lot of time spend doing DOM layout.

**Comment by TheModMaker** [comment]
I may have reproduced something similar.  I noticed that sometimes there is a delay when the cue is visible.  When this happens, I noticed that the cue was being added multiple times.  This happens because the `ResizeObserver` is firing multiple times and we add and remove the cue multiple times.  Try commenting out the following line to see if it helps:

https://github.com/google/shaka-player/blob/e1b3debb331528135dbca382e161fe269efc07d4/lib/text/ui_text_displayer.js#L90

**Comment by kocoten1992** [comment]
Thanks, we are getting somewhere!!
Comment out `ResizeObserver` does not help (put a blank canvas on top text div does help though), like:

```js
// in constructor ui_text_displayer.js

/** @type {HTMLCanvasElement} */
this.canvasContainer_ = shaka.util.Dom.createHTMLCanvasElement();
this.canvasContainer_.classList.add('shaka-text-canvas-container');

this.videoContainer_.appendChild(this.canvasContainer_); // this need to be on top of text div
```

```css
.shaka-text-canvas-container {
    position: absolute;
    width: 100%;
    height: 100%;
}
```

**Comment by joeyparrish** [comment]
It's possible that this has to do with how and when the browser chooses to update or composite layers.  If the addition of a canvas layer on top of the text improves sync, there may be a more straightforward solution.  (I recall having memory issues in a web-based project many years ago that were solved by changing CSS to avoid the creation of layers in the compositor.)

**Comment by kocoten1992** [comment]
So, should I make a PR for this ?

I don't have a better idea nor motivated enough to find another (as this one isn't terrible - if documented right).

**Comment by joeyparrish** [comment]
A PR for adding a canvas on top?  That feels hacky to me, and doesn't address the root cause, whatever that might be.  We would probably not merge that.

A PR for some CSS-based or JS-based solution to fix layout timing?  Yes, that would be great.
